# Generated by Django 5.0.3 on 2024-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
